---
title: "IKEA PRICES"
author: "Sumair Shah"
date: "2/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidymodels)
library(plotly)
ikea <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-03/ikea.csv")
```

```{r}
ikea %>% 
  select(X1,price,depth:width) %>% 
  pivot_longer(depth:width,names_to = "dim") %>% 
  ggplot(aes(x = value, y = price,color = dim)) + 
  geom_point(alpha = 0.4) + 
  scale_y_log10() + facet_wrap(~dim,scales = "free_x") + labs(x = NULL)

```
```{r}
ikea_df <- ikea %>% 
  select(price, name,category,depth,height,width) %>% 
  mutate(price = log10(price)) %>% 
  mutate_if(is.character,factor)

```

```{r}

set.seed(1234)

ikea_split <- initial_split(ikea_df,strata = price)
#training
ikea_train <- training(ikea_split)
# testing
ikea_testing <- testing(ikea_split)

set.seed(234)
ikea_folds <- bootstraps(ikea_train, strata = price)

```


```{r}
install.packages('usemodels')
library(usemodels)

use_ranger(price ~.,data = ikea_train)


```


```{r}
install.packages("textrecipes")
install.packages('ranger')
library(ranger)
library(textrecipes)

ranger_recipe <- 
  recipe(formula = price ~ ., data = ikea_train) %>% 
  step_other(name,category, threshold = .01) %>% 
  step_clean_levels(name,category) %>% 
  step_knnimpute(depth,height,width)

ranger_spec <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_mode("regression") %>% 
  set_engine("ranger") 

ranger_workflow <- 
  workflow() %>% 
  add_recipe(ranger_recipe) %>% 
  add_model(ranger_spec) 

set.seed(73895)

doParallel::registerDoParallel()
ranger_tune <-
  tune_grid(ranger_workflow, resamples = ikea_folds, grid = 11)
```
```{r}
show_best(ranger_tune, metric = "rmse")
show_best(ranger_tune,metric = "rsq")
```

```{r}
autoplot(ranger_tune)

```
```{r}
final_rf <- ranger_workflow %>% 
  finalize_workflow(select_best(ranger_tune,metric = 'rsq'))



```

```{r}

ikea_fit <- last_fit(final_rf, ikea_split)
ikea_fit$.metrics[[1]]

```
```{r}
collect_metrics(ikea_fit)

```
```{r}
ggplotly(collect_predictions(ikea_fit) %>% 
ggplot(aes(price,.pred)) +
  geom_abline(lty = 2, color = "gray50")+
  geom_point(alpha = 0.5, color = "midnightblue") +
  coord_fixed())
```
```{r}

predict(ikea_fit$.workflow[[1]],ikea_testing[3:15,])


```

```{r}
library(vip)

imp_spec <- ranger_spec %>% 
  finalize_model(select_best(ranger_tune)) %>% 
  set_engine("ranger",importance = "permutation")
  

workflow() %>%
  add_recipe(ranger_recipe) %>%
  add_model(imp_spec) %>%
  fit(ikea_train) %>%
  pull_workflow_fit() %>%
  vip(aesthetics = list(alpha = 0.8, fill = "midnightblue"))




```
}
